-- H A I R  B Y  C H R I S S Y — Supabase schema
--
-- Paste this into the Supabase SQL editor and run it once.
-- Dashboard -> SQL Editor -> New query -> paste -> Run.
--
-- Two tables, on purpose:
--
--   hbc_bookings   one row per appointment. This is the thing that grows, that
--                  you want to sort by date, and that is worth being able to
--                  look at in the Supabase table editor when a client rings up.
--
--   hbc_state      one row, holding everything else — services, working hours,
--                  rules, blocked dates, the reference counter, the alert log
--                  and the push keys. All of it is configuration: small, read
--                  constantly, changed rarely. Splitting it into six tables
--                  would buy nothing and cost a migration every time a setting
--                  is added.

-- ---------------------------------------------------------------- bookings

create table if not exists hbc_bookings (
  id           text primary key,          -- bk_… generated by the app
  ref          text unique not null,      -- HBC-1001, the client-facing reference
  date         date not null,
  start_min    integer not null,          -- minutes from midnight
  end_min      integer not null,
  status       text not null,             -- confirmed | pending-payment | cancelled
  service_id   text,
  client_name  text,
  -- The complete booking record. The app reads and writes whole objects, so
  -- this is the source of truth; the columns above are promoted copies so the
  -- table is queryable and readable in the dashboard.
  data         jsonb not null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists hbc_bookings_date_idx   on hbc_bookings (date);
create index if not exists hbc_bookings_status_idx on hbc_bookings (status);

-- ------------------------------------------------------------------- state

create table if not exists hbc_state (
  id         integer primary key default 1,
  data       jsonb not null,
  updated_at timestamptz not null default now(),
  -- There is exactly one row. The constraint makes a second one impossible
  -- rather than merely unlikely.
  constraint hbc_state_single_row check (id = 1)
);

-- --------------------------------------------------------------------- RLS
--
-- The app connects with the service_role key, which bypasses row-level
-- security entirely — so RLS is not what protects this data day to day; the
-- key living only on the server is.
--
-- It is enabled anyway, with no policies, so that anon and authenticated roles
-- get nothing. That way a leaked ANON key — the one that is safe to publish and
-- therefore the one most likely to end up somewhere public — cannot read a
-- single client's phone number.

alter table hbc_bookings enable row level security;
alter table hbc_state    enable row level security;

-- ------------------------------------------------------------------ bucket
--
-- The photo bucket cannot be created from SQL. In the dashboard:
--
--   Storage -> New bucket
--     Name:   booking-photos
--     Public: OFF          <-- these are clients' private photographs
--
-- Leave it private. The app serves the bytes itself, through an authenticated
-- admin route, so nothing is ever reachable by URL alone.
